少数派: https://raw.githubusercontent.com/yinan-c/RSS-GPT/main/docs/sspai.xml
36krai: https://raw.githubusercontent.com/yinan-c/RSS-GPT/main/docs/36kr-ai.xml
36kr: https://raw.githubusercontent.com/yinan-c/RSS-GPT/main/docs/36kr.xml
brettterpstra: https://raw.githubusercontent.com/yinan-c/RSS-GPT/main/docs/brett-terpstra.xml
byte: https://raw.githubusercontent.com/yinan-c/RSS-GPT/main/docs/byte-tank.xml
ifanr: https://raw.githubusercontent.com/yinan-c/RSS-GPT/main/docs/ifanr.xml
paulgraham: https://github.com/yinan-c/RSS-GPT/blob/main/docs/paul-graham.xml
RobbKnight: https://raw.githubusercontent.com/yinan-c/RSS-GPT/main/docs/robb-knight.xml
steph-ango: https://raw.githubusercontent.com/yinan-c/RSS-GPT/main/docs/steph-ango.xml
